[env:esp32-p4-ev-board]
platform = https://github.com/platformio/platform-espressif32.git#develop
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32p4

# This specific version is currently the most stable for P4
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.0

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    adafruit/MAX6675 library @ ^1.1.2