name: P4 qPCR Cloud Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build Project
        # We run prune to ensure a fresh download of the 3.0.4 framework
        run: |
          pio system prune --force
          pio run